# Generated by Django 6.1.1 on 2026-09-18 09:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pds_actif', models.BooleanField(default=False)),
                ('services_concernes_actifs', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Configuration des rôles',
                'verbose_name_plural': 'Configuration des rôles',
            },
        ),
        migrations.CreateModel(
            name='Imputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, unique=True)),
                ('portee', models.TextField(help_text='Description officielle de la portée')),
                ('instruction_claire', models.TextField(blank=True, help_text='Traduction en langage clair pour les services opérationnels')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('type_courrier', models.CharField(choices=[('arrivee', 'Courrier Arrivée'), ('depart', 'Courrier Départ')], max_length=10)),
                ('date_enregistrement', models.DateField(default=django.utils.timezone.now)),
                ('origine_destinataire', models.CharField(max_length=255)),
                ('objet', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('enregistre', 'Enregistré'), ('transmis_sg', 'Transmis au SG'), ('en_traitement', 'En traitement'), ('transmis_pds', 'Transmis au PDS'), ('imputation_definitive', 'Imputation définitive posée'), ('archive', 'Archivé'), ('redige', 'Rédigé'), ('en_validation', 'En validation'), ('signe', 'Signé'), ('expedie', 'Expédié'), ('classe', 'Classé')], default='enregistre', max_length=30)),
                ('confidentiel', models.BooleanField(default=False)),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='dossiers/%Y/%m/')),
                ('verrouille', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dossiers_crees', to=settings.AUTH_USER_MODEL)),
                ('service_actuel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_en_cours', to='courrier.service')),
            ],
        ),
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal', to='courrier.dossier')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-horodatage'],
            },
        ),
        migrations.CreateModel(
            name='ImputationDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField(blank=True)),
                ('est_definitive', models.BooleanField(default=False)),
                ('date_application', models.DateTimeField(auto_now_add=True)),
                ('applique_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imputations_appliquees', to='courrier.dossier')),
                ('imputation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courrier.imputation')),
                ('service_destinataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courrier.service')),
            ],
        ),
    ]
