# Generated by Django 6.1.1 on 2026-09-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courrier', '0002_seed_imputations'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationroles',
            name='delai_relance_jours',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='imputationdossier',
            name='relance_envoyee',
            field=models.BooleanField(default=False),
        ),
    ]
