# Generated by Django 6.1.1 on 2026-09-18 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courrier', '0002_seed_imputations'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='service',
            field=models.ForeignKey(blank=True, help_text="Service d'appartenance, uniquement pour le rôle 'service_concerne'", null=True, on_delete=django.db.models.deletion.SET_NULL, to='courrier.service'),
        ),
    ]
