SERVICES_DEFAUT = [
    ('DSTM', 'Direction de la Santé, de la Tranquillité et de la Mobilité'),
    ('DPM', 'Direction de la Planification et du Management'),
    ('DDF', 'Direction des Finances'),
    ('DAJ', 'Direction des Affaires Juridiques'),
    ('SG', 'Secrétariat Général'),
    ('PDS', 'Présidence de la Délégation Spéciale'),
    ('DDEL', 'Direction de l’Equipement et du Logement'),
    ('RAGIM', 'Ressources et gestion administrative'),
    ('SP.SG', 'Service particulier du Secrétariat Général'),
    ('DADF', 'Direction de l’Administration et des Finances'),
    ('DEAHP', 'Direction de l’Education, de l’Animation et de l’Hygiène Publique'),
    ('Questre', 'Questre'),
    ('PRM', 'Programme de résilience et de modernisation'),
    ('CEDJ', 'Cellule d’Etudes et de Développement Juridique'),
    ('DAFB', 'Direction de l’Appui aux Finances et à la Budgétisation'),
    ('DSP', 'Direction de la Sécurité Publique'),
    ('DEPMT', 'Direction de l’Environnement, de la Propreté et du Milieu de Travail'),
    ('SP/MAIRE', 'Service particulier du Maire'),
    ('SRH', 'Service des Ressources Humaines'),
    ('CT', 'Cellule de Traitement'),
    ('IVP', 'Inspection de la Voix Publique'),
    ('2VP', 'Deuxième Vice-Présidence'),
    ('CEDL', 'Cellule d’Etudes et de Développement Local'),
    ('CAGSC', 'Cellule d’Appui à la Gestion des Services Communaux'),
    ('CAEF', 'Cellule d’Appui à l’Exécution des Finances'),
    ('CATGF', 'Cellule d’Appui aux Travaux et aux Grands Financements'),
    ('Chargé de mission', 'Chargé de mission'),
    ('Chargé d’étude', 'Chargé d’étude'),
]
